In [1]:
import pandas as pd

In [2]:
dict1 ={'Name':['Priyang','Aadhya','Krisha','Vedant','Parshv',
                'Mittal','Archana'],
                'Marks':[98,89,99,87,90,83,99],
                'Gender':['Male','Female','Female','Male','Male',
                         'Female','Female']
               }
df1=pd.DataFrame(dict1)
df1

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

### 1.Display Top 3 Rows of The Dataset

In [3]:
df1.head(3)

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female

### 2.Check Last 3 Rows of the Dataset

In [4]:
df1.tail(3)

      Name  Marks  Gender
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

### 3. Find Shape of Dataset

In [5]:
df1.shape

(7, 3)

In [6]:
print("Rows",df1.shape[0])
print("Columns",df1.shape[1])

Rows 7
Columns 3

### 4.Get information about our dataset

In [7]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      object
 1   Marks   7 non-null      int64
 2   Gender  7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

### 5.Check Null Values

In [8]:
df1.isnull()

    Name  Marks  Gender
0  False  False   False
1  False  False   False
2  False  False   False
3  False  False   False
4  False  False   False
5  False  False   False
6  False  False   False

### 6.Get Overall Statistics

In [10]:
df1.describe(include='all')

           Name      Marks  Gender
count         7   7.000000       7
unique        7        NaN       2
top     Priyang        NaN  Female
freq          1        NaN       4
mean        NaN  92.142857     NaN
std         NaN   6.491753     NaN
min         NaN  83.000000     NaN
25%         NaN  88.000000     NaN
50%         NaN  90.000000     NaN
75%         NaN  98.500000     NaN
max         NaN  99.000000     NaN

### 7.Find Unique values from gender column

In [11]:
df1['Gender'].unique()

array(['Male', 'Female'], dtype=object)

### 8.Find the number of Unique values from gender column

In [13]:
df1['Gender'].nunique()

2

### 9.Display Count of Unique values

In [14]:
df1['Gender'].value_counts()

Gender
Female    4
Male      3
Name: count, dtype: int64

### 10.Find total students having marks between 90 to 100

In [15]:
df1[df1['Marks']>=90]

      Name  Marks  Gender
0  Priyang     98    Male
2   Krisha     99  Female
4   Parshv     90    Male
6  Archana     99  Female

In [16]:
len(df1[(df1['Marks']>=90) & (df1['Marks']<=100)])

4

In [17]:
sum(df1['Marks'].between(90,100))

4

### 11.Find Average Marks

In [18]:
df1['Marks'].mean()

np.float64(92.14285714285714)

### 12.Apply Method

In [19]:
def marks(x):
    return x//2

In [20]:
df1['Half_mark']=df1['Marks'].apply(marks)

In [21]:
df1

      Name  Marks  Gender  Half_mark
0  Priyang     98    Male         49
1   Aadhya     89  Female         44
2   Krisha     99  Female         49
3   Vedant     87    Male         43
4   Parshv     90    Male         45
5   Mittal     83  Female         41
6  Archana     99  Female         49

In [23]:
df1['Marks'].apply(lambda x:x/2)

0    49.0
1    44.5
2    49.5
3    43.5
4    45.0
5    41.5
6    49.5
Name: Marks, dtype: float64

In [24]:
df1['Name'].apply(len)

0    7
1    6
2    6
3    6
4    6
5    6
6    7
Name: Name, dtype: int64

### 13.MAp Function

In [25]:
df1

      Name  Marks  Gender  Half_mark
0  Priyang     98    Male         49
1   Aadhya     89  Female         44
2   Krisha     99  Female         49
3   Vedant     87    Male         43
4   Parshv     90    Male         45
5   Mittal     83  Female         41
6  Archana     99  Female         49

In [28]:
df1['Male_Female']=df1["Gender"].map({'Male':1,'Female':0})

In [29]:
df1

      Name  Marks  Gender  Half_mark  Male_Female
0  Priyang     98    Male         49            1
1   Aadhya     89  Female         44            0
2   Krisha     99  Female         49            0
3   Vedant     87    Male         43            1
4   Parshv     90    Male         45            1
5   Mittal     83  Female         41            0
6  Archana     99  Female         49            0

### 14.Drop the column(s)

In [30]:
df1

      Name  Marks  Gender  Half_mark  Male_Female
0  Priyang     98    Male         49            1
1   Aadhya     89  Female         44            0
2   Krisha     99  Female         49            0
3   Vedant     87    Male         43            1
4   Parshv     90    Male         45            1
5   Mittal     83  Female         41            0
6  Archana     99  Female         49            0

In [31]:
df1.drop('Male_Female',axis=1)

      Name  Marks  Gender  Half_mark
0  Priyang     98    Male         49
1   Aadhya     89  Female         44
2   Krisha     99  Female         49
3   Vedant     87    Male         43
4   Parshv     90    Male         45
5   Mittal     83  Female         41
6  Archana     99  Female         49

In [33]:
df1.drop(['Male_Female','Half_mark'],axis=1,inplace = True)

In [34]:
df1

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

### 15.Print Names of the columns

In [35]:
df1.columns

Index(['Name', 'Marks', 'Gender'], dtype='object')

In [36]:
df1.index

RangeIndex(start=0, stop=7, step=1)

### 16.Sort The Dataframes As per the marks

In [37]:
df1

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [38]:
df1.sort_values(by='Marks')

      Name  Marks  Gender
5   Mittal     83  Female
3   Vedant     87    Male
1   Aadhya     89  Female
4   Parshv     90    Male
0  Priyang     98    Male
2   Krisha     99  Female
6  Archana     99  Female

In [39]:
df1.sort_values(by='Marks',ascending=False)

      Name  Marks  Gender
2   Krisha     99  Female
6  Archana     99  Female
0  Priyang     98    Male
4   Parshv     90    Male
1   Aadhya     89  Female
3   Vedant     87    Male
5   Mittal     83  Female

### 17.Display marks of Females only

In [40]:
df1

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [41]:
df1[df1['Gender']=='Female' ] [['Name','Marks']]

      Name  Marks
1   Aadhya     89
2   Krisha     99
5   Mittal     83
6  Archana     99

In [42]:
df1[df1['Gender'].isin(['Female'])][['Name','Marks']]

      Name  Marks
1   Aadhya     89
2   Krisha     99
5   Mittal     83
6  Archana     99